---
- name: "Install LB Service"
  package:
    name: "{{ simple_lb.package }}"
    state: present
- name: "Start Web Service"
  service:
    name: "{{ simple_lb.service }}"
    state: started
    enabled: yes
- name: "Copy Web Content"
  copy:
    src: "{{ role_path }}/files/haproxy.cfg"
    dest: "{{ simple_lb.cfgroot }}//haproxy.cfg"
- name: Restart service haproxy, in all cases
  ansible.builtin.service:
    name: "{{ simple_lb.service }}"
    state: restarted